name: Feature Request
description: Request a new feature or enhancement
title: "[Feature]: "
labels: enhancement

body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out feature request!
        
        Please make sure this feature hasn't been requested previously by checking open & closed issues.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a description of the feature or enhancement you would like to see.
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give any additional information on the feature request like proposed solutions, links, screenshots, etc.
